<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.16" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageReference Include="Polly" Version="8.4.1" />
		<PackageReference Include="RedLock.net" Version="2.3.2" />
		<PackageReference Include="StackExchange.Redis" Version="2.10.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
		<PackageReference Include="System.IO.Pipelines" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.29.3" />
		<PackageReference Include="Grpc.Tools" Version="2.67.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Packets\Proto\packets.proto" GrpcServices="None" />
	</ItemGroup>

</Project>
