#!/usr/bin/env python3
"""
generate_ai_sdlc_docs.py
AI_SDLC 자동 생성 문서를 업데이트한다.
- Docs/ai-sdlc/skill-reference.md : 스킬 목록 테이블
- Docs/ai-sdlc/automation-map.md  : 자동화 컴포넌트 맵
- Docs/ai-sdlc/gates.md           : 게이트 판정 기준

각 파일의 <!-- MARKER_START --> ... <!-- MARKER_END --> 구간을 갱신한다.
docs.yml의 Generate AI SDLC docs 스텝으로 실행된다.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SKILLS_DIR = ROOT / ".claude" / "skills"
WORKFLOWS_DIR = ROOT / ".github" / "workflows"
SCRIPTS_DIR = ROOT / ".github" / "scripts"
AI_SDLC_DOCS = ROOT / "Docs" / "ai-sdlc"

HEADER_COMMENT = "<!-- AUTO-GENERATED — DO NOT EDIT MANUALLY -->\n<!-- This file is generated by .github/scripts/generate_ai_sdlc_docs.py -->\n<!-- Run: python .github/scripts/generate_ai_sdlc_docs.py -->\n\n"


def update_marker(content: str, marker: str, new_body: str) -> str:
    pattern = rf"(<!-- {marker}_START -->).*?(<!-- {marker}_END -->)"
    replacement = rf"\1\n{new_body}\n\2"
    updated, count = re.subn(pattern, replacement, content, flags=re.DOTALL)
    if count == 0:
        print(f"[warn] marker {marker}_START/END not found -- skipped")
    return updated


def collect_skills() -> list[dict]:
    """SKILLS_DIR에서 스킬 목록을 수집한다."""
    skills = []
    db_write_pattern = re.compile(r"db_write\.py.*?--action\s+(\S+)", re.DOTALL)
    lock_pattern = re.compile(r"job_lock\.py\s+(claim|release|heartbeat)")

    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue
        content = skill_md.read_text(encoding="utf-8")

        db_actions = list(set(db_write_pattern.findall(content)))
        lock_ops = list(set(lock_pattern.findall(content)))

        # 한 줄 설명 추출 (첫 번째 # 헤더 다음 줄)
        lines = content.splitlines()
        description = ""
        for i, line in enumerate(lines):
            if line.startswith("# ") and i + 1 < len(lines):
                desc_line = lines[i + 1].strip()
                if desc_line:
                    description = desc_line[:60]
                break

        skills.append({
            "name": f"`/{skill_dir.name}`",
            "path": f"`.claude/skills/{skill_dir.name}/`",
            "db_write": "Yes" if db_actions else "—",
            "job_lock": ", ".join(lock_ops) if lock_ops else "—",
            "description": description,
        })
    return skills


def collect_workflows() -> list[dict]:
    """GitHub Actions 워크플로 목록을 수집한다."""
    workflows = []
    trigger_pattern = re.compile(r"^on:\s*\n((?:  .+\n?)+)", re.MULTILINE)
    step_name_pattern = re.compile(r"- name: (.+)")

    for wf_file in sorted(WORKFLOWS_DIR.glob("*.yml")):
        content = wf_file.read_text(encoding="utf-8")

        # 트리거 추출 (첫 번째 on: 블록)
        triggers = []
        on_match = re.search(r"^on:\s*\n((?:  .+\n?)+)", content, re.MULTILINE)
        if on_match:
            trigger_lines = on_match.group(1)
            for line in trigger_lines.splitlines():
                stripped = line.strip().rstrip(":")
                if stripped and not stripped.startswith("#"):
                    triggers.append(stripped)
        trigger_str = ", ".join(triggers[:3]) if triggers else "—"

        # 이름 추출 (name: 필드)
        name_match = re.search(r"^name:\s*(.+)", content, re.MULTILINE)
        wf_name = name_match.group(1).strip() if name_match else wf_file.stem

        workflows.append({
            "file": wf_file.name,
            "name": wf_name,
            "triggers": trigger_str,
        })
    return workflows


def collect_scripts() -> list[dict]:
    """주요 Python 스크립트 목록을 수집한다."""
    scripts = []
    known = {
        "db_write.py": "SDLC DB 헬퍼 (upsert-job, insert-step, get-gates 등)",
        "job_lock.py": "Job Lock claim/release/heartbeat",
        "check_sdlc_consistency.py": "DB ↔ task JSON 정합성 검사",
        "backup_sdlc_db.sh": "PostgreSQL 백업 (7일 보관)",
        "record_failure.py": "로컬 수동 실패 기록",
        "migrate_tasks_to_postgres.py": "task JSON → DB 마이그레이션",
        "generate_cost_log_from_db.py": "DB 기반 cost-log 생성",
        "generate_ai_sdlc_docs.py": "AI_SDLC 문서 자동 생성 (이 스크립트)",
        "check_docs_toc.py": "DocFX toc 미등재 파일 감지",
        "count_tokens.py": "Claude API 토큰 집계",
        "insert_model_run.py": "ai_model_runs 삽입",
        "get_task_risk.py": "task 위험도 조회",
    }
    for name, desc in known.items():
        path = SCRIPTS_DIR / name
        exists = "✔" if path.exists() else "—"
        scripts.append({"name": f"`{name}`", "desc": desc, "exists": exists})
    return scripts


def build_skill_reference_table(skills: list[dict]) -> str:
    rows = ["| 스킬 | 경로 | DB write | Job Lock |",
            "|------|------|----------|----------|"]
    for s in skills:
        rows.append(f"| {s['name']} | {s['path']} | {s['db_write']} | {s['job_lock']} |")
    return "\n".join(rows)


def build_automation_map_table(workflows: list[dict]) -> str:
    rows = ["| 파일 | 이름 | 트리거 |",
            "|------|------|--------|"]
    for w in workflows:
        rows.append(f"| `{w['file']}` | {w['name']} | {w['triggers']} |")
    return "\n".join(rows)


def build_scripts_table(scripts: list[dict]) -> str:
    rows = ["| 스크립트 | 용도 | 존재 |",
            "|---------|------|------|"]
    for s in scripts:
        rows.append(f"| {s['name']} | {s['desc']} | {s['exists']} |")
    return "\n".join(rows)


def update_file_if_changed(path: Path, new_content: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if old == new_content:
        print(f"[skip] {path.name} — no changes")
        return False
    path.write_text(new_content, encoding="utf-8")
    print(f"[updated] {path.name}")
    return True


def main() -> int:
    changed = 0

    skills = collect_skills()
    workflows = collect_workflows()
    scripts = collect_scripts()

    # skill-reference.md
    sr_path = AI_SDLC_DOCS / "skill-reference.md"
    if sr_path.exists():
        sr_content = sr_path.read_text(encoding="utf-8")
        new_table = build_skill_reference_table(skills)
        sr_content = update_marker(sr_content, "SKILL_TABLE", new_table)
        if update_file_if_changed(sr_path, sr_content):
            changed += 1
    else:
        print(f"[skip] {sr_path.name} — file not found")

    # automation-map.md
    am_path = AI_SDLC_DOCS / "automation-map.md"
    if am_path.exists():
        am_content = am_path.read_text(encoding="utf-8")
        wf_table = build_automation_map_table(workflows)
        am_content = update_marker(am_content, "WORKFLOW_TABLE", wf_table)
        sc_table = build_scripts_table(scripts)
        am_content = update_marker(am_content, "SCRIPT_TABLE", sc_table)
        if update_file_if_changed(am_path, am_content):
            changed += 1
    else:
        print(f"[skip] {am_path.name} — file not found")

    print(f"\n완료: {changed}개 파일 업데이트됨")
    return 0


if __name__ == "__main__":
    sys.exit(main())
