<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>17010383-15a0-4abf-bea5-7d543755cd9e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\PlatformA.Library\PlatformA.Library.csproj" />
  </ItemGroup>

</Project>
