// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlatformA.SdlcDB.Lib;

#nullable disable

namespace PlatformA.SdlcDB.Lib.Migrations
{
    [DbContext(typeof(SdlcDbContext))]
    [Migration("20260605012538_AddGitHubFailureIdentity")]
    partial class AddGitHubFailureIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sdlc")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlatformA.SdlcDB.Lib.Entities.AiFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("branch");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FailureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_type");

                    b.Property<bool?>("FixableByAi")
                        .HasColumnType("boolean")
                        .HasColumnName("fixable_by_ai");

                    b.Property<long?>("GitHubJobId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_job_id");

                    b.Property<long?>("GitHubRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_run_id");

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("LogExcerpt")
                        .HasColumnType("text")
                        .HasColumnName("log_excerpt");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.HasKey("Id")
                        .HasName("pk_ai_failures");

                    b.HasIndex("Branch")
                        .HasDatabaseName("ix_ai_failures_branch");

                    b.HasIndex("CommitSha")
                        .HasDatabaseName("ix_ai_failures_commit_sha");

                    b.HasIndex("FailureType")
                        .HasDatabaseName("ix_ai_failures_failure_type");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_ai_failures_job_id");

                    b.HasIndex("GitHubRunId", "GitHubJobId", "FailureType")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_failures_github_job_failure")
                        .HasFilter("git_hub_run_id IS NOT NULL AND git_hub_job_id IS NOT NULL");

                    b.ToTable("ai_failures", "sdlc");
                });

            modelBuilder.Entity("PlatformA.SdlcDB.Lib.Entities.AiJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AdrRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("adr_required");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("branch");

                    b.Property<long?>("CacheTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_tokens");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long?>("ConsumeTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("consume_tokens");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<string>("Impact")
                        .HasColumnType("jsonb")
                        .HasColumnName("impact");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inserted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("PrUrl")
                        .HasColumnType("text")
                        .HasColumnName("pr_url");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<bool>("ReviewCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("review_completed");

                    b.Property<string>("SourceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_json");

                    b.Property<int?>("Sprint")
                        .HasColumnType("integer")
                        .HasColumnName("sprint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("task_name");

                    b.Property<bool>("TestGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("test_generated");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_ai_jobs");

                    b.HasIndex("Branch")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_jobs_branch");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ai_jobs_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ai_jobs_status");

                    b.ToTable("ai_jobs", "sdlc");
                });

            modelBuilder.Entity("PlatformA.SdlcDB.Lib.Entities.AiJobStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_name");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_ai_job_steps");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_ai_job_steps_job_id");

                    b.HasIndex("StepName")
                        .HasDatabaseName("ix_ai_job_steps_step_name");

                    b.ToTable("ai_job_steps", "sdlc");
                });

            modelBuilder.Entity("PlatformA.SdlcDB.Lib.Entities.AiModelRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CacheCreationTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("ModelName")
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RawUsage")
                        .HasColumnType("text")
                        .HasColumnName("raw_usage");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long?>("StepId")
                        .HasColumnType("bigint")
                        .HasColumnName("step_id");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_tokens");

                    b.HasKey("Id")
                        .HasName("pk_ai_model_runs");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_ai_model_runs_job_id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_ai_model_runs_step_id");

                    b.ToTable("ai_model_runs", "sdlc");
                });

            modelBuilder.Entity("PlatformA.SdlcDB.Lib.Entities.AiFailure", b =>
                {
                    b.HasOne("PlatformA.SdlcDB.Lib.Entities.AiJob", "Job")
                        .WithMany("Failures")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ai_failures_ai_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PlatformA.SdlcDB.Lib.Entities.AiJobStep", b =>
                {
                    b.HasOne("PlatformA.SdlcDB.Lib.Entities.AiJob", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_job_steps_ai_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PlatformA.SdlcDB.Lib.Entities.AiModelRun", b =>
                {
                    b.HasOne("PlatformA.SdlcDB.Lib.Entities.AiJob", "Job")
                        .WithMany("ModelRuns")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ai_model_runs_ai_jobs_job_id");

                    b.HasOne("PlatformA.SdlcDB.Lib.Entities.AiJobStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ai_model_runs_ai_job_steps_step_id");

                    b.Navigation("Job");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("PlatformA.SdlcDB.Lib.Entities.AiJob", b =>
                {
                    b.Navigation("Failures");

                    b.Navigation("ModelRuns");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
