// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformA.MySqlDB.Lib.DBWebApp;

#nullable disable

namespace PlatformA.MySqlDB.Lib.Migrations.WebApp
{
    [DbContext(typeof(DbWebAppContext))]
    [Migration("20260622001147_AddGameTypeAndRatingToMatchRecords")]
    partial class AddGameTypeAndRatingToMatchRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Item", b =>
                {
                    b.Property<long>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Pid"));

                    b.Property<int>("Grade")
                        .HasColumnType("int")
                        .HasColumnName("grade");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<long>("Tid")
                        .HasColumnType("bigint")
                        .HasColumnName("tid");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint")
                        .HasColumnName("uid");

                    b.HasKey("Pid")
                        .HasName("pk_item");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.MatchRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ended_at");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("game_type");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int")
                        .HasColumnName("player1id");

                    b.Property<int>("Player1Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000)
                        .HasColumnName("player1rating");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int")
                        .HasColumnName("player2id");

                    b.Property<int>("Player2Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000)
                        .HasColumnName("player2rating");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("room_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("pk_match_records");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("ix_match_records_winner_id");

                    b.HasIndex("Player1Id", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_match_records_player1id_created_at");

                    b.HasIndex("Player2Id", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_match_records_player2id_created_at");

                    b.ToTable("match_records", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_players_username");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.PlayerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("losses");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("TotalGames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_games");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("wins");

                    b.HasKey("Id")
                        .HasName("pk_player_stats");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_stats_player_id");

                    b.ToTable("player_stats", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Shop", b =>
                {
                    b.Property<long>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Pid"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<long>("Tid")
                        .HasColumnType("bigint")
                        .HasColumnName("tid");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint")
                        .HasColumnName("uid");

                    b.HasKey("Pid")
                        .HasName("pk_shop");

                    b.ToTable("shop", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.User", b =>
                {
                    b.Property<long>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Pid"));

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint")
                        .HasColumnName("uid");

                    b.HasKey("Pid")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.MatchRecord", b =>
                {
                    b.HasOne("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", "Player1")
                        .WithMany("MatchesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_records_players_player1id");

                    b.HasOne("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", "Player2")
                        .WithMany("MatchesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_records_players_player2id");

                    b.HasOne("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_match_records_players_winner_id");

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.PlayerStat", b =>
                {
                    b.HasOne("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", "Player")
                        .WithOne("Stat")
                        .HasForeignKey("PlatformA.MySqlDB.Lib.DBWebApp.Entities.PlayerStat", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_stats_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", b =>
                {
                    b.Navigation("MatchesAsPlayer1");

                    b.Navigation("MatchesAsPlayer2");

                    b.Navigation("Stat");
                });
#pragma warning restore 612, 618
        }
    }
}
