// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformA.MySqlDB.Lib.DBWebApp;

#nullable disable

namespace PlatformA.MySqlDB.Lib.Migrations.WebApp
{
    [DbContext(typeof(DbWebAppContext))]
    partial class DbWebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Item", b =>
                {
                    b.Property<int?>("Grade")
                        .HasColumnType("int(11)")
                        .HasColumnName("grade");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<long?>("Pid")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("pid");

                    b.Property<long?>("Tid")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("tid");

                    b.Property<long?>("Uid")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("uid");

                    b.HasIndex(new[] { "Pid" }, "pk");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.MatchRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("match_records", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.PlayerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("player_stats", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Shop", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<long?>("Pid")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("pid");

                    b.Property<long?>("Tid")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("tid");

                    b.Property<long?>("Uid")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("uid");

                    b.HasIndex(new[] { "Pid" }, "pk");

                    b.ToTable("shop", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.User", b =>
                {
                    b.Property<int?>("Level")
                        .HasColumnType("int(11)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<long?>("Pid")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("pid");

                    b.Property<long?>("Uid")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("uid");

                    b.HasIndex(new[] { "Pid" }, "pk");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.MatchRecord", b =>
                {
                    b.HasOne("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", "Player1")
                        .WithMany("MatchesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", "Player2")
                        .WithMany("MatchesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.PlayerStat", b =>
                {
                    b.HasOne("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", "Player")
                        .WithOne("Stat")
                        .HasForeignKey("PlatformA.MySqlDB.Lib.DBWebApp.Entities.PlayerStat", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PlatformA.MySqlDB.Lib.DBWebApp.Entities.Player", b =>
                {
                    b.Navigation("MatchesAsPlayer1");

                    b.Navigation("MatchesAsPlayer2");

                    b.Navigation("Stat");
                });
#pragma warning restore 612, 618
        }
    }
}
